package com.capstone.bwlovers.global.exception;

public enum ClientExceptionCode {

    // 전체
    INTERNAL_SERVER_ERROR,
    ILLEGAL_ARGUMENT,

    // Auth / Login
    LOGIN_ERROR,
    AUTH_SERVER_ERROR,
    AUTH_TOKEN_EMPTY,
    ACCESS_TOKEN_EMPTY,
    REFRESH_TOKEN_EMPTY,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_TOKEN_MISMATCH,
    ALREADY_LOGGED_TOKEN,
    FORBIDDEN,

    // User
    USER_NOT_FOUND,
    HEALTH_STATUS_NOT_FOUND,
    PREGNANCY_INFO_NOT_FOUND,
    JOB_NOT_FOUND,

    // AI
    AI_INVALID_REQUEST,
    AI_PROCESSING_FAILED,
    AI_SERVER_ERROR,
    AI_RESULT_NOT_FOUND,
    AI_SAVE_EMPTY_SELECTION,
    AI_ALREADY_SAVED,

    // JSON
    JSON_SERIALIZATION_FAILED,
    JSON_DESERIALIZATION_FAILED,

    // Redis
    REDIS_SAVE_FAILED,
    REDIS_READ_FAILED,
    REDIS_CONNECTION_FAILED,

    // Insurance
    INSURANCE_NOT_FOUND,

    // OCR
    OCR_TEMP_FILE_SAVE_FAILED,
    OCR_TEMP_FILE_READ_FAILED,
    OCR_TEMP_FILE_DELETE_FAILED,
    OCR_INVALID_REQUEST,
    OCR_TOO_MANY_PAGES,
    OCR_EMPTY_FILE,
    OCR_FILE_TOO_LARGE,
    OCR_UNSUPPORTED_FILE_TYPE,
    OCR_JOB_NOT_FOUND,
    OCR_LOCAL_STORAGE_NOT_SUPPORTED

}
